oxid-symfony-kernel:
    bundles: { cihaeuser/hotspots: Ci\Oxid\Hotspots\CiOxidHotspotsBundle, sioweb/oxid-api: Sioweb\Oxid\Api\SiowebOxidApiBundle, symfony/security-bundle: Symfony\Bundle\SecurityBundle\SecurityBundle }
