services:
    sioweb.oxid.kernel.listener.request:
        class: Sioweb\Oxid\Kernel\EventListener\RequestListener
        arguments:
            - "@service_container"
            - "@sioweb.oxid.kernel.bundles"
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 900 }