services:
    oxidcommunity.symfonykernel.listener.request.before:
        class: OxidCommunity\SymfonyKernel\EventListener\RequestListener
        arguments:
            - "@service_container"
            - "@oxidcommunity.symfonykernel.bundles"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequestBefore, priority: 999 }

    oxidcommunity.symfonykernel.listener.request.after:
        class: OxidCommunity\SymfonyKernel\EventListener\RequestListener
        arguments:
            - "@service_container"
            - "@oxidcommunity.symfonykernel.bundles"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequestAfter, priority: 800 }