services:
    oxidcommunity.symfonykernel.bundles:
        synthetic: true
        public: true
    oxid_http_kernel:
        class: OxidCommunity\SymfonyKernel\HttpKernel\HttpKernel
        arguments:
            - "@event_dispatcher"
            - "@controller_resolver"
            - "@request_stack"